# Basics of Python and Numpy

In [1]:
print("hello world")

hello world


In [2]:
3+4

7

In [3]:
a=5
b=89
print("a={0} wow hi hello".format(a))
print("Binary a={0:b} and Hexadecimal b={1:x}".format(a,b))


a=5 wow hi hello
Binary a=101 and Hexadecimal b=59


### STRINGS

In [4]:
#STRING
string="Good Mornin"
print(string[0])
print(string[0:7])
print(string+'g')
print(string*2)
print(string[-2:])

G
Good Mo
Good Morning
Good MorninGood Mornin
in


In [5]:
string="hakuna matata"
space="      "
print(str.capitalize(string))

print(str.isalnum(string))

print(string.isalnum())

print(string.isdigit())

print(string.islower())

print(string.isspace())

print(space.isspace())

print(len(space))

print(max(string))

print(min(string))

print(string.upper())

Hakuna matata
False
False
False
True
False
True
6
u
 
HAKUNA MATATA


### LIST

In [6]:
#LIST
lst=["hi",1,45,"hello"]
print(lst[2:4])

[45, 'hello']


In [7]:
lst.append('gravity')
print(lst)
del lst[4]
print(lst)

print(len(lst))

print(lst+lst)

print(lst*5)

print(1 in lst)

l=lst.copy
print(l)

['hi', 1, 45, 'hello', 'gravity']
['hi', 1, 45, 'hello']
4
['hi', 1, 45, 'hello', 'hi', 1, 45, 'hello']
['hi', 1, 45, 'hello', 'hi', 1, 45, 'hello', 'hi', 1, 45, 'hello', 'hi', 1, 45, 'hello', 'hi', 1, 45, 'hello']
True
<built-in method copy of list object at 0x000000C79773AFC8>


### TUPLES

In [8]:
#TUPLES
tup=("hi",1,45,"hello")
print(tup[0])
print(tup[2:])

hi
(45, 'hello')


### DICTIONARY

In [9]:
#DICTIONARY
dictionary={'name':"Vijay Dinanath Chauhan",'id':7,63:87}
print(dictionary['id'])
print(dictionary[63])
print(dictionary.keys())
print(dictionary.values())

7
87
dict_keys(['name', 'id', 63])
dict_values(['Vijay Dinanath Chauhan', 7, 87])


### INPUT 

In [10]:
#INPUT
a=input("Enter a:")

Enter a:


In [11]:
b=eval(input("Enter 3 nos"))

Enter 3 nos


SyntaxError: unexpected EOF while parsing (<string>, line 0)

In [ ]:
a,b,c=eval(input("Enter a,b,c"))

In [ ]:
print(a,b,c)

In [12]:
a=[
    [1,2,3],
    [4,5,6]
]

In [13]:
print(a[0])

[1, 2, 3]


In [14]:
a=6 
b=7
a|b

7

In [15]:
not(a and b)

False

In [16]:
a=[
    [1,2,3],
    [4,5,6]
]
2 in a[0]

True

In [17]:
a=6
b=6
a is b


True

### IF ELIF ELSE

In [18]:
#IF ELIF ELSE
amount=eval(input("Enter amount"))
if amount<1000:
    discount=amount*0.05
    print ("Discount",discount)
elif amount<5000:
    discount=amount*0.10
    print ("Discount",discount)
else:
    discount=amount*0.15
    print ("Discount",discount)

Enter amount


SyntaxError: unexpected EOF while parsing (<string>, line 0)

In [19]:
count = 0
while count < 9:
    print ('The count is:', count)
    count = count + 1

print ("Good bye!")

The count is: 0
The count is: 1
The count is: 2
The count is: 3
The count is: 4
The count is: 5
The count is: 6
The count is: 7
The count is: 8
Good bye!


In [20]:
for var in list(range(5)):
    print(var)
print(type(var))

0
1
2
3
4
<class 'int'>


In [21]:
for letter in 'Good Morning':
    print(letter)

G
o
o
d
 
M
o
r
n
i
n
g


### FOR-ELSE

In [22]:
#FOR-ELSE
for l in "Hello, good morning!":
    if l is 'z':
        print("z is present")
        break
else:
    print("z is not present")

z is not present


In [23]:
p=3 
q=4
print(complex(p))
print(complex(p)+2+4j)
print(complex(p,q))

(3+0j)
(5+4j)
(3+4j)


In [24]:
import math
s=-10
t=12.20
print(abs(s),
      math.ceil(s),
      math.exp(s),
      math.floor(s),
      math.log(t))


10 -10 4.5399929762484854e-05 -10 2.501435951739211


In [25]:
print(max(2,4,8,9))
print(min(8,9,-2,6))
print(pow(2,4))
print(math.sqrt(121))

9
-2
16
11.0


In [26]:
import random
print(random.randint(3,100))
print(random.random())
print(random.uniform(5,500))

18
0.21871631762478594
261.7550577894149


### FUNCTIONS

In [27]:
#FUNCTIONS

def func(s):
    print("String passed in the argument will be passed")
    print(s)
    return s*2
    
new = func("All parameters (arguments) in the Python language are passed by reference.")
print(new)

String passed in the argument will be passed
All parameters (arguments) in the Python language are passed by reference.
All parameters (arguments) in the Python language are passed by reference.All parameters (arguments) in the Python language are passed by reference.


# NUMPY

In [28]:
#NUMPY
#Numpy is an open-source add-on module that provides common mathematical 
#and numerical routines as pre- compiled fast functions 

import numpy as np
#1D
a= np.array([1,2,3,4],float)
print(a)
print(type(a))
print(a[2:])
#2D
a=np.array([[1,2,3],[4,5,6]])
print(a)
print(a[0])
print(a[0][1])
print(a.shape)

[1. 2. 3. 4.]
<class 'numpy.ndarray'>
[3. 4.]
[[1 2 3]
 [4 5 6]]
[1 2 3]
2
(2, 3)


In [29]:
a=np.array(range(10),float)
print(a)
print(a.shape)
print()

a=a.reshape((5,2))
print(a)
print(a.shape)
print()

print(a.transpose())
print()

print(a.flatten())
print()

a=a.flatten()
b=np.array([23,53,65])
c=np.array([18,4,6,7])
print(np.concatenate((a,b,c)))

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
(10,)

[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]
(5, 2)

[[0. 2. 4. 6. 8.]
 [1. 3. 5. 7. 9.]]

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 23. 53. 65. 18.  4.  6.  7.]


In [30]:
print(np.ones((2,3)))
print()
      
print(np.zeros(7,dtype=int))

[[1. 1. 1.]
 [1. 1. 1.]]

[0 0 0 0 0 0 0]


In [31]:
a=np.array([4,5,7])
b=np.array([23,53,65])
print(a+b)
print(a-b)
print(a/b)
print(a*b)
print(a%b)
print(a**b)

[27 58 72]
[-19 -48 -58]
[0.17391304 0.09433962 0.10769231]
[ 92 265 455]
[4 5 7]
[          0 -1208458123  1159739911]


In [32]:
a=np.array([1,3])
b=np.array([2,5,8])
print(a+b)

ValueError: operands could not be broadcast together with shapes (2,) (3,) 

### BROADCASTING

In [ ]:
#BROADCASTING
#Arrays that do not match in the number of dimensions will be broadcasted 
#by Python to perform mathematical operations

a=np.array([[1,2],[3,4],[5,6],[7,8]])
b=np.array([10,11])
print(a)
print()
print(b)
print()
print(a+b)

### ARRAY ITERATION

In [ ]:
#ARRAY ITERATION
a=np.array(range(5))
for x in a:
    print(x)
    
print()
a=np.array([[1,2],[3,4],[5,6]])
for(x,y) in a:
    print(x*y)

In [ ]:
a=np.array([2,5,9])
print(np.sum(a))
print(np.prod(a))
print(np.mean(a))
print(np.var(a)) #variance
print(np.std(a)) #standard deviation
print(np.min(a))
print(np.max(a))
print(np.argmax(a)) #argument of min
print(np.argmin(a)) #argument of max
print(np.sort(a))

In [33]:
a=np.array([1,2,3])
b=np.array([0,1,1])
print(np.dot(a,b))
print(np.cross(a,b))

5
[-1 -1  1]


In [34]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.save('out',x)
x=np.load('out.npy')
print(x)

[0 1 2 3 4 5 6 7 8 9]
